import DashboardLayout from "@/components/DashboardLayout";
import { AIChatBox, type Message } from "@/components/AIChatBox";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, Check, ChevronLeft, CircleHelp, FileSearch, FlaskConical, ListChecks, Pencil, Play, ShieldAlert, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { useLocation, useRoute } from "wouter";
import { toast } from "sonner";

const entityKinds = ["compound", "api", "synthesis_step", "therapeutic_context", "date", "citation"] as const;
type EntityKind = (typeof entityKinds)[number];
type EditState = { id?: number; kind: EntityKind; label: string; details: string; pageNumber: string; sectionLabel: string };
const blankEdit: EditState = { kind: "compound", label: "", details: "", pageNumber: "", sectionLabel: "" };

const nextStage: Record<string, { status: "uploaded" | "extracting" | "needs_review" | "retrieving" | "analyzing" | "report_ready"; label: string } | undefined> = {
  uploaded: { status: "extracting", label: "Start extraction" },
  extracting: { status: "needs_review", label: "Open extraction review" },
  needs_review: { status: "retrieving", label: "Start evidence retrieval" },
  retrieving: { status: "analyzing", label: "Start chemistry analysis" },
  analyzing: { status: "report_ready", label: "Prepare review report" },
  failed: { status: "uploaded", label: "Retry assessment" },
};

export default function AssessmentDetail() {
  const [, params] = useRoute("/workspace/analysis/:id");
  const [, setLocation] = useLocation();
  const runId = Number(params?.id);
  const detailQuery = trpc.sanjeevani.assessment.useQuery({ analysisRunId: runId }, { enabled: runId > 0 });
  const data = detailQuery.data;
  const utils = trpc.useUtils();
  const [edit, setEdit] = useState<EditState>(blankEdit);
  const [assistantMode, setAssistantMode] = useState<"explain" | "guide">("guide");
  const refresh = () => utils.sanjeevani.assessment.invalidate({ analysisRunId: runId });
  const confirm = trpc.sanjeevani.confirmEntity.useMutation({ onSuccess: refresh });
  const add = trpc.sanjeevani.addEntity.useMutation({ onSuccess: () => { setEdit(blankEdit); refresh(); toast.success("Extraction item added for review."); } });
  const update = trpc.sanjeevani.updateEntity.useMutation({ onSuccess: () => { setEdit(blankEdit); refresh(); toast.success("Provenance correction saved and returned to review."); } });
  const transition = trpc.sanjeevani.transitionAnalysis.useMutation({ onSuccess: refresh, onError: (error) => toast.error(error.message) });
  const report = trpc.sanjeevani.generateReviewReport.useMutation({ onSuccess: () => { refresh(); toast.success("Evidence-backed report prepared for review."); } });
  const workspaceId = data?.workspace.id ?? 0;
  const history = trpc.sanjeevani.assistant.history.useQuery({ workspaceId }, { enabled: workspaceId > 0 });
  const assistant = trpc.sanjeevani.assistant.ask.useMutation({ onSuccess: () => utils.sanjeevani.assistant.history.invalidate({ workspaceId }) });
  const messages = useMemo<Message[]>(() => (history.data ?? []).map((message) => ({ role: message.role, content: message.content })), [history.data]);

  if (detailQuery.isLoading) return <DashboardLayout><p className="mx-auto max-w-6xl py-16 text-sm text-slate-400">Loading private assessment…</p></DashboardLayout>;
  if (!data) return <DashboardLayout><div className="mx-auto max-w-5xl py-16"><Button onClick={() => setLocation("/workspace")} variant="outline" className="border-white/15 bg-white/[0.03] text-white hover:bg-white/10 hover:text-white"><ChevronLeft className="mr-1 size-4" />Workspace</Button><p className="mt-6 text-sm text-slate-400">This assessment is not available in your workspace.</p></div></DashboardLayout>;
  const action = nextStage[data.run.status];
  const submitEdit = () => {
    if (!edit.label.trim()) return toast.error("Add a label before saving the extraction item.");
    const input = { kind: edit.kind, label: edit.label.trim(), details: edit.details || undefined, pageNumber: edit.pageNumber ? Number(edit.pageNumber) : undefined, sectionLabel: edit.sectionLabel || undefined };
    if (edit.id) update.mutate({ entityId: edit.id, ...input }); else add.mutate({ analysisRunId: runId, ...input });
  };
  const advance = () => {
    if (!action) return;
    if (action.status === "report_ready") report.mutate({ analysisRunId: runId }); else transition.mutate({ analysisRunId: runId, nextStatus: action.status });
  };

  return <DashboardLayout><div className="mx-auto max-w-7xl"><header className="flex flex-col justify-between gap-5 border-b border-white/8 pb-7 lg:flex-row lg:items-end"><div><button onClick={() => setLocation("/workspace")} className="mono flex items-center gap-1 text-[10px] uppercase tracking-[0.16em] text-slate-500 hover:text-primary"><ChevronLeft className="size-3" />Workspace</button><p className="mono mt-5 text-[10px] uppercase tracking-[0.18em] text-primary">Private assessment / {data.run.status}</p><h1 className="editorial-display mt-2 text-4xl text-white">{data.submission.title}</h1><p className="mt-3 text-sm text-slate-400">{data.submission.institution || "Institution not recorded"} · {data.run.currentStage}</p></div><div className="flex flex-wrap items-center gap-3"><Badge className={`border-0 px-3 py-1.5 ${data.run.status === "failed" ? "bg-amber-300/10 text-amber-200" : data.run.status === "deleted" ? "bg-white/8 text-slate-400" : "bg-primary/10 text-primary"}`}>{data.run.progress}% · {data.run.status}</Badge>{data.run.status !== "deleted" && <Button variant="ghost" onClick={() => transition.mutate({ analysisRunId: runId, nextStatus: "deleted" })} className="text-xs text-slate-500 hover:bg-white/5 hover:text-slate-300">Archive</Button>}{action && <Button onClick={advance} disabled={transition.isPending || report.isPending} className="rounded-full bg-primary text-primary-foreground hover:bg-primary/90"><Play className="mr-2 size-3.5" />{transition.isPending || report.isPending ? "Updating…" : action.label}</Button>}</div></header>

  <div className="mt-7 grid gap-6 xl:grid-cols-[1fr_360px]"><div className="min-w-0 space-y-6"><section className="rounded-[1.5rem] border border-white/8 bg-[#1d2032]/70 p-6"><SectionHeading icon={ListChecks} title="Structured extraction review" text="Correct every label and its page/section provenance before evidence retrieval progresses." /><div className="mt-6 space-y-3">{data.entities.length ? data.entities.map((entity) => <article key={entity.id} className="flex flex-col justify-between gap-4 rounded-xl border border-white/8 bg-white/[0.025] p-4 sm:flex-row sm:items-center"><div><div className="flex flex-wrap gap-2"><Badge className="border-0 bg-white/8 text-slate-300">{entity.kind}</Badge><Badge className={`border-0 ${entity.confirmed ? "bg-primary/10 text-primary" : "bg-amber-300/10 text-amber-200"}`}>{entity.confirmed ? "confirmed" : "needs review"}</Badge></div><p className="mt-2 text-sm font-medium text-white">{entity.label}</p>{entity.details && <p className="mt-1 text-xs leading-5 text-slate-400">{entity.details}</p>}<p className="mono mt-2 text-[10px] uppercase tracking-[0.13em] text-slate-500">Page {entity.pageNumber ?? "—"} · {entity.sectionLabel || "section not tagged"}</p></div><div className="flex shrink-0 gap-2"><Button size="sm" variant="outline" onClick={() => setEdit({ id: entity.id, kind: entity.kind, label: entity.label, details: entity.details ?? "", pageNumber: entity.pageNumber ? String(entity.pageNumber) : "", sectionLabel: entity.sectionLabel ?? "" })} className="border-white/12 bg-white/[0.03] text-white hover:bg-white/10 hover:text-white"><Pencil className="mr-1 size-3.5" />Edit</Button><Button size="sm" variant="outline" onClick={() => confirm.mutate({ entityId: entity.id, confirmed: !entity.confirmed })} className="border-white/12 bg-white/[0.03] text-white hover:bg-white/10 hover:text-white">{entity.confirmed ? "Flag" : <><Check className="mr-1 size-3.5" />Confirm</>}</Button></div></article>) : <Empty text="No extraction items are available yet. Add a researcher-verified item to create the review record." />}</div>
  <div className="mt-6 rounded-xl border border-primary/15 bg-primary/[0.035] p-4"><p className="mono text-[10px] uppercase tracking-[0.14em] text-primary">{edit.id ? "Correct extraction item" : "Add extraction item"}</p><div className="mt-4 grid gap-3 md:grid-cols-2"><select value={edit.kind} onChange={(event) => setEdit({ ...edit, kind: event.target.value as EntityKind })} className="h-10 rounded-md border border-white/10 bg-[#161828] px-3 text-sm text-white">{entityKinds.map((kind) => <option key={kind} value={kind}>{kind.replace("_", " ")}</option>)}</select><Input value={edit.label} onChange={(event) => setEdit({ ...edit, label: event.target.value })} placeholder="Entity label" className="border-white/10 bg-white/[0.035] text-white" /><Input value={edit.pageNumber} onChange={(event) => setEdit({ ...edit, pageNumber: event.target.value })} inputMode="numeric" placeholder="Page number" className="border-white/10 bg-white/[0.035] text-white" /><Input value={edit.sectionLabel} onChange={(event) => setEdit({ ...edit, sectionLabel: event.target.value })} placeholder="Section / citation provenance" className="border-white/10 bg-white/[0.035] text-white" /></div><Textarea value={edit.details} onChange={(event) => setEdit({ ...edit, details: event.target.value })} placeholder="Correction note, citation detail, or rationale" className="mt-3 min-h-20 border-white/10 bg-white/[0.035] text-white" /><div className="mt-3 flex gap-2"><Button onClick={submitEdit} disabled={add.isPending || update.isPending} className="bg-primary text-primary-foreground hover:bg-primary/90">{edit.id ? "Save correction" : "Add for review"}</Button>{edit.id && <Button variant="ghost" onClick={() => setEdit(blankEdit)} className="text-slate-400 hover:bg-white/5 hover:text-white">Cancel</Button>}</div></div></section>
  <section className="rounded-[1.5rem] border border-white/8 bg-[#1d2032]/70 p-6"><SectionHeading icon={FileSearch} title="RAG collision evidence" text="Page-aware sources use the required screening states, never patentability percentages." /><div className="mt-6 space-y-3">{data.evidence.length ? data.evidence.map((item) => <article key={item.id} className="rounded-xl border border-white/8 bg-white/[0.025] p-5"><div className="flex flex-wrap items-center justify-between gap-3"><Badge className="border-0 bg-primary/10 text-primary">{item.collisionState}</Badge><span className="mono text-[10px] uppercase tracking-[0.13em] text-slate-500">{item.sourceType}</span></div><p className="mt-3 text-sm font-medium text-white">{item.sourceTitle}</p><p className="mt-2 text-xs leading-6 text-slate-400">{item.rationale}</p><p className="mt-3 text-[11px] text-slate-500">{item.pageReference || "No page reference"} · provenance {item.provenanceVersion}</p></article>) : <Empty text="Move the analysis through retrieval and reporting to create source-scoped evidence records." />}</div></section>
  <section className="rounded-[1.5rem] border border-white/8 bg-[#1d2032]/70 p-6"><SectionHeading icon={FlaskConical} title="Chemistry, route, and feasibility" text="Chemical identity and route analysis are distinct from document-level collision signals." /><div className="mt-6 space-y-3">{data.chemistry.length ? data.chemistry.map((item) => <article key={item.id} className="rounded-xl border border-white/8 bg-white/[0.025] p-5"><div className="flex items-start justify-between gap-4"><div><Badge className="border-0 bg-white/8 text-slate-300">{item.category}</Badge><p className="mt-3 text-sm font-medium text-white">{item.label}</p><p className="mt-2 text-xs leading-6 text-slate-400">{item.details}</p></div><Badge className="border-0 bg-amber-300/10 text-amber-200">{item.status}</Badge></div></article>) : <Empty text="Chemistry findings appear only after an approved source-backed RDKit/OPSIN service responds." />}</div></section>
  <section className="rounded-[1.5rem] border border-white/8 bg-[#1d2032]/70 p-6"><SectionHeading icon={ShieldAlert} title="Evidence-backed action report" text="Screening output is for review and escalation, not a legal or clinical conclusion." />{data.report ? <div className="mt-6 rounded-2xl border border-primary/15 bg-primary/[0.04] p-5"><p className="text-base font-semibold text-white">{data.report.title}</p><p className="mt-3 text-sm leading-7 text-slate-300">{data.report.executiveSummary}</p><p className="mono mt-5 text-[10px] uppercase tracking-[0.15em] text-primary">Recommended escalation</p><p className="mt-1 text-sm text-white">{data.report.recommendedEscalation}</p><p className="mt-5 rounded-xl border border-amber-300/15 bg-amber-300/[0.05] p-4 text-xs leading-6 text-amber-100">{data.report.disclaimer}</p></div> : <div className="mt-6"><Empty text="Complete the analysis stages before preparing the evidence-backed report." /></div>}</section></div>
  <aside><div className="sticky top-7 rounded-[1.5rem] border border-white/8 bg-[#1d2032]/80 p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Sparkles className="size-4 text-primary" /><p className="text-sm font-semibold text-white">Guidance assistant</p></div><div className="flex rounded-lg bg-white/[0.05] p-0.5"><button onClick={() => setAssistantMode("explain")} className={`rounded-md px-2 py-1 text-[10px] ${assistantMode === "explain" ? "bg-primary text-primary-foreground" : "text-slate-400"}`}>Explain</button><button onClick={() => setAssistantMode("guide")} className={`rounded-md px-2 py-1 text-[10px] ${assistantMode === "guide" ? "bg-primary text-primary-foreground" : "text-slate-400"}`}>Guide</button></div></div><p className="mt-2 text-[11px] leading-5 text-slate-500">Read-only workspace context. No legal, clinical, or patentability conclusions; no mutations without a separate confirmation flow.</p><AIChatBox messages={messages} onSendMessage={(content) => assistant.mutate({ workspaceId, analysisRunId: runId, mode: assistantMode, content })} isLoading={assistant.isPending} height="440px" className="mt-4 border-white/8 bg-[#161828]" placeholder="Ask about status, evidence, urgency, or next steps" emptyStateMessage="Ask how to finish this assessment" suggestedPrompts={["What should I review next?", "Explain the evidence boundary", "What is missing?"]} /></div></aside></div></div></DashboardLayout>;
}

function SectionHeading({ icon: Icon, title, text }: { icon: typeof ListChecks; title: string; text: string }) { return <div className="flex gap-3"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="size-5" /></span><div><h2 className="text-base font-semibold text-white">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{text}</p></div></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-white/12 p-7 text-center"><CircleHelp className="mx-auto size-5 text-primary" /><p className="mt-3 text-sm text-slate-400">{text}</p></div>; }
