import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { ScreeningSignals } from "@/components/ScreeningSignals";
import { ArrowRight, FileSearch, ShieldCheck } from "lucide-react";
import { useLocation } from "wouter";

export default function EvidenceReports() {
  const [, setLocation] = useLocation();
  const overview = trpc.sanjeevani.overview.useQuery();
  return <DashboardLayout><div className="mx-auto max-w-6xl"><div className="border-b border-white/8 pb-7"><p className="mono text-[10px] uppercase tracking-[0.18em] text-primary">Evidence and reports</p><h1 className="editorial-display mt-2 text-4xl text-white">Reports are an escalation aid.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Collision states, chemistry findings, urgency context, and feasibility notes remain source-aware screening information.</p></div><section className="mt-7 rounded-[1.5rem] border border-white/8 bg-[#1d2032]/70 p-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="mono text-[10px] uppercase tracking-[0.16em] text-primary">Assessment flow</p><p className="mt-2 text-sm text-slate-400">This count is a workflow view, not a novelty, safety, or patentability score.</p></div><p className="mono text-xs text-slate-500">{overview.data?.assessments.length ?? 0} total records</p></div><ScreeningSignals assessmentCount={overview.data?.assessments.length ?? 0} /></section><div className="mt-7 grid gap-4">{overview.data?.assessments.length ? overview.data.assessments.map(({ run, submission }) => <article key={run.id} className="flex flex-col gap-5 rounded-2xl border border-white/8 bg-[#1d2032]/70 p-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-4"><span className="grid size-11 place-items-center rounded-xl bg-primary/10 text-primary"><FileSearch className="size-5" /></span><div><p className="text-base font-medium text-white">{submission.title}</p><p className="mt-1 text-xs text-slate-500">Current report status follows the analysis lifecycle.</p><div className="mt-3 flex gap-2"><Badge className="border-0 bg-white/8 text-slate-300">{run.status}</Badge><Badge className="border-0 bg-primary/10 text-primary">{run.progress}% complete</Badge></div></div></div><Button variant="outline" onClick={() => setLocation(`/workspace/analysis/${run.id}`)} className="border-white/12 bg-white/[0.03] text-white hover:bg-white/10 hover:text-white">Review evidence <ArrowRight className="ml-1 size-3.5" /></Button></article>) : <div className="rounded-2xl border border-dashed border-white/12 p-10 text-center"><ShieldCheck className="mx-auto size-7 text-primary" /><p className="mt-4 text-sm text-slate-300">Create an assessment to begin an evidence-backed report.</p></div>}</div></div></DashboardLayout>;
}
