import { Button } from "@/components/ui/button";
import HaikeiBackdrop from "@/components/HaikeiBackdrop";
import { motion, useScroll, useTransform } from "motion/react";
import { ArrowDownRight, ArrowRight, BookOpenCheck, FileSearch, FlaskConical, Network, ShieldCheck, Sparkles } from "lucide-react";
import { useLocation } from "wouter";

const stages = [
  { number: "01", title: "Read the work", text: "Upload the manuscript, record the disclosure context, and surface the research entities that require human confirmation.", icon: FileSearch },
  { number: "02", title: "Separate the signals", text: "Keep document collision evidence, molecule/route findings, and timing guidance visibly distinct and source-aware.", icon: FlaskConical },
  { number: "03", title: "Move with clarity", text: "Prepare a cited action report for a researcher, TTO, chemist, or qualified patent professional.", icon: BookOpenCheck },
];

export default function LandingPage() {
  const [, setLocation] = useLocation();
  const { scrollYProgress } = useScroll();
  const orbY = useTransform(scrollYProgress, [0, 0.5], [0, 170]);
  const cardY = useTransform(scrollYProgress, [0, 0.45], [0, -68]);

  return (
    <div className="overflow-x-hidden bg-[#151727] text-slate-100">
      <header className="fixed inset-x-0 top-0 z-50 border-b border-white/8 bg-[#151727]/75 px-5 py-4 backdrop-blur-xl md:px-10">
        <div className="mx-auto flex max-w-7xl items-center justify-between">
          <button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary"><span className="mono text-xs uppercase tracking-[0.18em] text-primary">Sanjeevani</span><span className="ml-3 hidden text-xs text-slate-400 sm:inline">Research intelligence</span></button>
          <nav className="hidden items-center gap-6 text-xs text-slate-300 md:flex"><a href="#process" className="hover:text-primary">Process</a><a href="#boundaries" className="hover:text-primary">Boundaries</a><a href="#guidance" className="hover:text-primary">Patent guidance</a></nav>
          <Button size="sm" onClick={() => setLocation("/workspace")} className="rounded-full bg-primary px-4 text-primary-foreground hover:bg-primary/90">Open workspace <ArrowRight className="ml-1 size-3.5" /></Button>
        </div>
      </header>

      <main>
        <section className="noise-grid relative min-h-[880px] overflow-hidden px-5 pb-24 pt-36 md:px-10 md:pt-44">
          <HaikeiBackdrop />
          <motion.div style={{ y: orbY }} className="pointer-events-none absolute right-[-15rem] top-20 size-[37rem] rounded-full bg-[radial-gradient(circle_at_40%_40%,oklch(0.67_0.19_203_/_0.48),transparent_60%)] blur-2xl" />
          <div className="pointer-events-none absolute -left-28 bottom-0 h-96 w-[44rem] rounded-[60%] border border-primary/20 bg-primary/[0.035]" />
          <div className="relative mx-auto grid max-w-7xl gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center">
            <motion.div initial={{ opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.75, ease: [0.23, 1, 0.32, 1] }}>
              <div className="mb-7 flex items-center gap-3"><span className="h-px w-10 bg-primary" /><span className="mono text-[10px] uppercase tracking-[0.2em] text-primary">Pre-disclosure research desk</span></div>
              <h1 className="editorial-display max-w-3xl text-[3.6rem] leading-[0.95] text-white sm:text-7xl lg:text-[6.2rem]">Keep the science <span className="text-primary">in motion.</span></h1>
              <p className="mt-8 max-w-xl text-base leading-8 text-slate-300 md:text-lg">Sanjeevani helps research teams turn an unpublished paper into a structured, evidence-aware next action—before a valuable molecule, route, or research opportunity becomes harder to protect or translate.</p>
              <div className="mt-9 flex flex-wrap gap-3"><Button size="lg" onClick={() => setLocation("/workspace/new")} className="rounded-full bg-primary px-6 text-primary-foreground hover:bg-primary/90">Start an assessment <ArrowDownRight className="ml-2 size-4" /></Button><Button size="lg" variant="outline" onClick={() => document.getElementById("process")?.scrollIntoView({ behavior: "smooth" })} className="rounded-full border-white/15 bg-white/[0.03] px-6 text-white hover:bg-white/10 hover:text-white">See the process</Button></div>
              <p className="mt-5 text-xs leading-5 text-slate-500">Screening and decision support only. Not a legal patentability opinion, clinical conclusion, or filing service.</p>
            </motion.div>
            <motion.div style={{ y: cardY }} className="relative mx-auto w-full max-w-xl lg:mx-0">
              <motion.div initial={{ opacity: 0, scale: 0.94, rotate: 2 }} animate={{ opacity: 1, scale: 1, rotate: 0 }} transition={{ delay: 0.2, duration: 0.8, ease: [0.23, 1, 0.32, 1] }} className="glass-panel relative overflow-hidden rounded-[2rem] p-5 sm:p-7">
                <div className="paper-dots absolute inset-0 opacity-35" />
                <div className="relative">
                  <div className="flex items-center justify-between"><div><p className="mono text-[10px] uppercase tracking-[0.18em] text-primary">Active assessment</p><p className="mt-1 text-sm font-medium text-white">Molecular route study · draft</p></div><span className="rounded-full border border-primary/30 bg-primary/10 px-3 py-1 mono text-[10px] text-primary">needs_review</span></div>
                  <div className="mt-8 grid gap-3 sm:grid-cols-2"><Metric label="Extraction review" value="6 entities" note="2 require confirmation" /><Metric label="Evidence boundary" value="2 records" note="citations preserved" /><Metric label="Urgency posture" value="critical" note="review dates required" warning /><Metric label="Expert route" value="TTO review" note="prepare dossier" /></div>
                  <div className="mt-6 rounded-2xl border border-white/10 bg-[#10121f]/80 p-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-primary/10 text-primary"><Sparkles className="size-4" /></span><div><p className="text-xs font-medium text-white">Guidance assistant</p><p className="mt-0.5 text-[11px] text-slate-400">Explain the evidence or identify the next review action.</p></div></div><div className="mt-4 h-1.5 overflow-hidden rounded-full bg-white/8"><motion.div animate={{ width: ["22%", "76%", "42%"] }} transition={{ duration: 4.5, repeat: Infinity, ease: "easeInOut" }} className="h-full rounded-full bg-gradient-to-r from-primary to-violet-400" /></div></div>
                </div>
              </motion.div>
              <motion.div initial={{ opacity: 0, x: 34 }} animate={{ opacity: 1, x: 0 }} transition={{ delay: 0.5, duration: 0.7 }} className="absolute -right-5 -top-7 hidden rounded-2xl border border-white/10 bg-[#24273b]/95 p-4 shadow-2xl sm:block"><p className="mono text-[9px] uppercase tracking-[0.15em] text-slate-400">Evidence mode</p><p className="mt-1 text-sm font-medium text-white">Source-aware</p><div className="mt-3 flex gap-1"><i className="size-1.5 rounded-full bg-primary" /><i className="size-1.5 rounded-full bg-violet-400" /><i className="size-1.5 rounded-full bg-white/25" /></div></motion.div>
            </motion.div>
          </div>
        </section>

        <section id="process" className="relative border-y border-white/8 bg-[#10121f] px-5 py-24 md:px-10 md:py-32"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="mono text-[10px] uppercase tracking-[0.2em] text-primary">A deliberate three-stage flow</p><h2 className="editorial-display mt-4 text-4xl text-white sm:text-5xl">A paper is not a keyword search.</h2><p className="mt-5 text-base leading-7 text-slate-400">The work is reviewed as research: with entity provenance, separate evidence types, and a clear handoff to the people who should make the final decision.</p></div><div className="mt-14 grid gap-4 lg:grid-cols-3">{stages.map((stage, index) => <motion.article key={stage.number} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: 0.25 }} transition={{ delay: index * 0.12, duration: 0.55 }} whileHover={{ y: -8 }} className="group relative overflow-hidden rounded-[1.6rem] border border-white/10 bg-[#1a1c2d] p-7"><span className="absolute right-5 top-5 mono text-xs text-white/15">{stage.number}</span><span className="grid size-11 place-items-center rounded-2xl bg-primary/10 text-primary"><stage.icon className="size-5" /></span><h3 className="mt-8 text-xl font-semibold text-white">{stage.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{stage.text}</p><div className="mt-8 flex items-center gap-2 text-xs text-primary opacity-0 transition-opacity duration-200 group-hover:opacity-100">Structured, reviewable, traceable <ArrowRight className="size-3" /></div></motion.article>)}</div></div></section>

        <section id="boundaries" className="relative px-5 py-24 md:px-10 md:py-32"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr]"><div className="lg:sticky lg:top-28 lg:self-start"><p className="mono text-[10px] uppercase tracking-[0.2em] text-primary">Trust is the interface</p><h2 className="editorial-display mt-4 text-4xl text-white sm:text-5xl">Evidence does not become certainty by changing its color.</h2><p className="mt-6 max-w-md leading-7 text-slate-400">Sanjeevani keeps three reasoning systems visible instead of collapsing them into one confident answer.</p></div><div className="space-y-4"><ReasonCard index="A" title="RAG collision evidence" text="Page-aware and source-linked retrieval produces no_match_found, possible_overlap, strong_collision, or insufficient_evidence—not a patentability percentage." icon={Network} /><ReasonCard index="B" title="Molecule and route intelligence" text="Chemical identity, similarity, routes, hazards, and feasibility remain distinct from semantic document similarity." icon={FlaskConical} /><ReasonCard index="C" title="Urgency and filing guidance" text="Dates, jurisdiction, rule source, and human escalation are presented as screening context—not a universal legal countdown." icon={ShieldCheck} /></div></div></section>

        <section className="border-y border-white/8 bg-[#10121f] px-5 py-24 md:px-10"><div className="mx-auto grid max-w-7xl gap-6 lg:grid-cols-[.9fr_1.1fr]"><div><p className="mono text-[10px] uppercase tracking-[0.2em] text-primary">Privacy posture</p><h2 className="editorial-display mt-4 text-4xl text-white sm:text-5xl">Research stays private by default.</h2><p className="mt-5 max-w-lg leading-7 text-slate-400">Uploads are stored as private workspace objects. Sanjeevani separates researcher records from any future institutional comparison and never exposes another team’s paper, chunks, vectors, or report.</p></div><div className="grid gap-3 sm:grid-cols-2"><ReasonCard index="01" title="Private workspace scope" text="Research uploads, metadata, and analysis runs remain owner-scoped unless the researcher explicitly uses a controlled handoff." icon={ShieldCheck} /><ReasonCard index="02" title="Least-disclosure comparison" text="A future institutional match may surface a bounded state to authorized reviewers, never another institution’s confidential content." icon={Network} /></div></div></section>
        <section id="guidance" className="px-5 pb-28 pt-24 md:px-10"><div className="mx-auto max-w-7xl overflow-hidden rounded-[2rem] border border-primary/20 bg-[linear-gradient(125deg,#183541,#1b1c31_45%,#252040)] p-7 sm:p-10 md:p-14"><div className="grid items-end gap-8 lg:grid-cols-[1.2fr_.8fr]"><div><p className="mono text-[10px] uppercase tracking-[0.2em] text-primary">Patent guidance, without gatekeeping</p><h2 className="editorial-display mt-4 max-w-3xl text-4xl text-white sm:text-5xl">A clearer route from research work to expert review.</h2><p className="mt-5 max-w-2xl leading-7 text-slate-300">Build your filing-readiness checklist, understand the roles in the process, assemble a controlled dossier, and keep every high-consequence action human-confirmed.</p><Button onClick={() => setLocation("/workspace/patent-guidance")} className="mt-7 rounded-full bg-white px-5 text-[#17192a] hover:bg-white/90">Explore Patent Guidance <ArrowRight className="ml-2 size-4" /></Button></div><div className="rounded-2xl border border-white/12 bg-black/15 p-5"><p className="mono text-[10px] uppercase tracking-[0.16em] text-slate-300">Readiness checklist</p>{["Confirm inventor and institution details", "Record public-disclosure context", "Review molecule and route records", "Route to a qualified reviewer"].map((item, index) => <div key={item} className="mt-4 flex items-center gap-3 text-sm text-slate-200"><span className={`grid size-5 place-items-center rounded-full border ${index < 2 ? "border-primary/70 bg-primary/15 text-primary" : "border-white/25 text-white/40"}`}>{index < 2 ? "✓" : index + 1}</span>{item}</div>)}</div></div></div></section>
      </main>
      <footer className="border-t border-white/8 px-5 py-8 md:px-10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-3 text-xs text-slate-500 sm:flex-row"><span>© Sanjeevani · Research intelligence workspace</span><span>Screening and decision support only.</span></div></footer>
    </div>
  );
}

function Metric({ label, value, note, warning }: { label: string; value: string; note: string; warning?: boolean }) { return <div className="rounded-2xl border border-white/8 bg-white/[0.035] p-4"><p className="mono text-[9px] uppercase tracking-[0.14em] text-slate-500">{label}</p><p className={`mt-3 text-base font-medium ${warning ? "text-amber-300" : "text-white"}`}>{value}</p><p className="mt-1 text-[11px] text-slate-500">{note}</p></div>; }
function ReasonCard({ index, title, text, icon: Icon }: { index: string; title: string; text: string; icon: typeof Network }) { return <motion.article initial={{ opacity: 0, x: 30 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: 0.3 }} whileHover={{ x: 8 }} className="flex gap-5 rounded-2xl border border-white/10 bg-[#1d2032]/70 p-6 transition-colors hover:border-primary/30"><span className="mono text-sm text-primary">{index}</span><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white/5 text-slate-200"><Icon className="size-5" /></span><div><h3 className="text-lg font-semibold text-white">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></div></motion.article>; }
