import DashboardLayout from "@/components/DashboardLayout";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { trpc } from "@/lib/trpc";
import { ArrowRight, FileText, PlusCircle } from "lucide-react";
import { useLocation } from "wouter";

export default function MyResearch() {
  const [, setLocation] = useLocation();
  const overview = trpc.sanjeevani.overview.useQuery();
  return <DashboardLayout><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-4 border-b border-white/8 pb-7 sm:flex-row sm:items-end"><div><p className="mono text-[10px] uppercase tracking-[0.18em] text-primary">Private repository</p><h1 className="editorial-display mt-2 text-4xl text-white">My research</h1><p className="mt-3 text-sm text-slate-400">Every entry remains scoped to your authenticated workspace.</p></div><Button onClick={() => setLocation("/workspace/new")} className="rounded-full bg-primary text-primary-foreground"><PlusCircle className="mr-2 size-4" />New assessment</Button></div><div className="mt-7 grid gap-4">{overview.data?.assessments.length ? overview.data.assessments.map(({ run, submission }) => <article key={run.id} className="rounded-2xl border border-white/8 bg-[#1d2032]/70 p-5"><div className="flex flex-col justify-between gap-5 sm:flex-row"><div className="flex gap-4"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-white/5 text-primary"><FileText className="size-5" /></span><div><p className="text-base font-medium text-white">{submission.title}</p><p className="mt-1 text-xs text-slate-500">{submission.fileName || "Metadata-only assessment"} · {submission.institution || "No institution recorded"}</p><p className="mt-3 text-xs text-slate-400">Disclosure posture: <span className="text-slate-200">{submission.disclosureStatus}</span></p></div></div><div className="flex items-center gap-4"><Badge className="border-0 bg-primary/10 text-primary">{run.status}</Badge><Button variant="outline" onClick={() => setLocation(`/workspace/analysis/${run.id}`)} className="border-white/12 bg-white/[0.03] text-white hover:bg-white/10 hover:text-white">Open <ArrowRight className="ml-1 size-3.5" /></Button></div></div></article>) : <div className="rounded-2xl border border-dashed border-white/12 p-10 text-center"><p className="text-sm text-slate-300">Your private research repository is empty.</p><Button variant="outline" onClick={() => setLocation("/workspace/new")} className="mt-5 border-white/15 bg-white/[0.03] text-white hover:bg-white/10 hover:text-white">Add research work</Button></div>}</div></div></DashboardLayout>;
}
