import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { trpc } from "@/lib/trpc";
import { BookOpenCheck, CheckCircle2, ExternalLink, FileCheck2, Scale, ShieldCheck, UsersRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const checklist = ["Confirm inventor and ownership details", "Record conception, disclosure, and publication context", "Confirm molecules, APIs, and route records", "Collect experimental support and comparative advantage", "Review public evidence and unresolved questions", "Escalate the approved dossier to a qualified reviewer"];
const sources = [
  { title: "WIPO Patents", jurisdiction: "General education", reviewed: "15 Aug 2026", url: "https://www.wipo.int/en/web/patents", text: "An educational starting point on patent information, inventions, products, and processes." },
  { title: "WIPO PCT System", jurisdiction: "International pathway", reviewed: "15 Aug 2026", url: "https://www.wipo.int/en/web/pct-system", text: "A source for learning about an international application route and later national-phase decisions." },
  { title: "Indian Patent Office Manual via WIPO Lex", jurisdiction: "India · historical procedural reference", reviewed: "15 Aug 2026", url: "https://www.wipo.int/wipolex/en/legislation/details/7648", text: "A procedural reference that must be checked against current law, rules, and qualified professional advice." },
];

export default function PatentGuidance() {
  const [completed, setCompleted] = useState<number[]>([]);
  const [confirmed, setConfirmed] = useState(false);
  const overview = trpc.sanjeevani.overview.useQuery();
  const handoff = trpc.sanjeevani.prepareReviewHandoff.useMutation({ onSuccess: () => toast.success("Review handoff recorded. No data was shared externally."), onError: (error) => toast.error(error.message) });
  const toggle = (index: number) => setCompleted((items) => items.includes(index) ? items.filter((item) => item !== index) : [...items, index]);
  return <DashboardLayout><div className="mx-auto max-w-6xl"><div className="grid gap-8 border-b border-white/8 pb-8 lg:grid-cols-[1.1fr_.9fr]"><div><p className="mono text-[10px] uppercase tracking-[0.18em] text-primary">Patent Guidance</p><h1 className="editorial-display mt-2 text-4xl text-white">Make the next process legible.</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400">This space helps researchers prepare for expert review. It explains the workflow and readiness requirements; it does not provide a legal opinion, calculate a filing deadline, or submit an application.</p></div><div className="rounded-2xl border border-amber-300/15 bg-amber-300/[0.05] p-5"><Badge className="border-0 bg-amber-300/10 text-amber-200">Jurisdiction-aware content required</Badge><p className="mt-3 text-xs leading-6 text-slate-300">Every educational source is labelled with its jurisdiction and review date. Sanjeevani does not assume a universal grace period or a legal deadline.</p></div></div>
  <section className="mt-8 grid gap-4 md:grid-cols-3"><GuideCard icon={BookOpenCheck} title="Understand the roles" text="Researcher, institution, TTO, patent professional, chemist, and manufacturing reviewer have distinct responsibilities." /><GuideCard icon={Scale} title="Prepare the record" text="Organize evidence and dates into a review-ready record before deciding whether to publish, file, or seek more experimentation." /><GuideCard icon={UsersRound} title="Escalate deliberately" text="Share only user-approved dossier sections with an authorized reviewer. No external contact happens automatically." /></section>
  <section className="mt-8 rounded-[1.5rem] border border-white/8 bg-[#1d2032]/70 p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-primary/10 text-primary"><FileCheck2 className="size-5" /></span><div><h2 className="text-base font-semibold text-white">Filing-readiness checklist</h2><p className="mt-1 text-xs text-slate-500">Complete the items that apply before preparing an expert-review dossier.</p></div></div><div className="mt-6 grid gap-3 md:grid-cols-2">{checklist.map((item, index) => <label key={item} className="flex cursor-pointer items-start gap-3 rounded-xl border border-white/8 bg-white/[0.025] p-4"><Checkbox checked={completed.includes(index)} onCheckedChange={() => toggle(index)} className="mt-0.5 border-white/30 data-[state=checked]:border-primary data-[state=checked]:bg-primary" /><div><p className="text-sm leading-6 text-slate-300">{item}</p>{completed.includes(index) && <p className="mt-1 text-[11px] text-primary">Recorded in this local readiness view</p>}</div></label>)}</div><div className="mt-6 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-primary/15 bg-primary/[0.035] p-4"><p className="text-xs leading-5 text-slate-400">{completed.length}/{checklist.length} readiness items recorded. Preparing a handoff does not share information or initiate a filing.</p><Dialog><DialogTrigger asChild><Button disabled={!completed.length || !overview.data?.workspace.id} className="rounded-full bg-primary text-primary-foreground hover:bg-primary/90">Prepare review handoff</Button></DialogTrigger><DialogContent className="border-white/10 bg-[#171929] text-white"><DialogHeader><DialogTitle>Confirm reviewer-handoff preparation</DialogTitle><DialogDescription className="text-slate-400">This creates no external contact and submits no filing. It records your selected readiness items for later human review.</DialogDescription></DialogHeader><label className="mt-4 flex items-start gap-3 text-sm text-slate-300"><Checkbox checked={confirmed} onCheckedChange={(value) => setConfirmed(value === true)} className="mt-0.5" />I understand that Sanjeevani provides screening and workflow support only, and that qualified review is required.</label><DialogFooter><Button disabled={!confirmed || handoff.isPending} onClick={() => overview.data?.workspace.id && handoff.mutate({ workspaceId: overview.data.workspace.id, checklist: completed.map((index) => checklist[index]) })} className="bg-primary text-primary-foreground hover:bg-primary/90">{handoff.isPending ? "Recording…" : "Confirm preparation"}</Button></DialogFooter></DialogContent></Dialog></div></section>
  <section className="mt-8"><div className="flex items-end justify-between gap-4"><div><p className="mono text-[10px] uppercase tracking-[0.18em] text-primary">Educational source library</p><h2 className="editorial-display mt-2 text-3xl text-white">Know where guidance came from.</h2></div><ShieldCheck className="size-6 text-primary" /></div><div className="mt-5 grid gap-4 lg:grid-cols-3">{sources.map((source) => <article key={source.title} className="rounded-2xl border border-white/8 bg-[#1d2032]/70 p-5"><div className="flex flex-wrap gap-2"><Badge className="border-0 bg-white/8 text-slate-300">{source.jurisdiction}</Badge><Badge className="border-0 bg-primary/10 text-primary">Reviewed {source.reviewed}</Badge></div><h3 className="mt-5 text-base font-semibold text-white">{source.title}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{source.text}</p><a href={source.url} target="_blank" rel="noreferrer" className="mt-5 inline-flex items-center gap-1 text-xs text-primary hover:underline">Open source <ExternalLink className="size-3.5" /></a></article>)}</div></section></div></DashboardLayout>;
}

function GuideCard({ icon: Icon, title, text }: { icon: typeof BookOpenCheck; title: string; text: string }) { return <article className="rounded-2xl border border-white/8 bg-[#1d2032]/70 p-5"><Icon className="size-5 text-primary" /><h2 className="mt-6 text-base font-semibold text-white">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-400">{text}</p></article>; }
